#!/usr/bin/env python3
"""
ServiceNow MCP Integration Module
Core functions for ServiceNow REST API operations.

Author: Jabu (Senior Developer)
Instance: dev228466
Table: sys_email
"""

import os
import sys
import json
import hashlib
import re
from typing import Dict, List, Optional, Any, Union
from datetime import datetime, timedelta
from dataclasses import dataclass

import pysnow
from pysnow import Client


@dataclass
class ServiceNowConfig:
    """Configuration for ServiceNow connection."""
    instance: str
    username: str
    password: str
    base_url: Optional[str] = None
    
    @classmethod
    def from_env_file(cls, env_path: str = None) -> "ServiceNowConfig":
        """Load config from env file."""
        if env_path is None:
            env_path = os.path.expanduser("~/.openclaw/workspace/servicenow.env")
        
        config = {}
        with open(env_path, "r") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, val = line.split("=", 1)
                config[key] = val
        
        instance_url = config.get("SERVICENOW_INSTANCE_URL", "")
        instance = instance_url.replace("https://", "").replace(".service-now.com/", "").replace("/", "")
        
        return cls(
            instance=instance,
            username=config.get("SERVICENOW_USERNAME", ""),
            password=config.get("SERVICENOW_PASSWORD", ""),
            base_url=instance_url.rstrip("/")
        )


class ServiceNowMCPError(Exception):
    """Base exception for ServiceNow MCP operations."""
    pass


class ConnectionError(ServiceNowMCPError):
    """Failed to connect to ServiceNow."""
    pass


class RecordExistsError(ServiceNowMCPError):
    """Record already exists (deduplication)."""
    pass


class WatermarkDetectedError(ServiceNowMCPError):
    """Auto-reply/watermark detected - would cause email loop."""
    pass


class ServiceNowMCP:
    """
    ServiceNow MCP Integration Client.
    
    Provides health checks, CRUD operations, deduplication,
    and watermark detection for email processing.
    """
    
    # Auto-reply header patterns to detect email loops
    WATERMARK_HEADERS = [
        "auto-submitted",
        "x-auto-response-suppress",
        "precedence",
        "x-autoresponder",
        "x-autoreply",
        "x-ms-exchange-generated-message-origin",
        "x-mail-autoreply",
        "x-loop",
        "x-mailing-list",
        "list-id",
        "feedback-id",
        "x-campaign",
        "x-autogenerated",
        "x-autoreply-from",
        "x-mailer-daemon",
    ]
    
    # Header values indicating auto-reply
    WATERMARK_VALUES = [
        "auto-replied",
        "auto-generated",
        "auto-notified",
        "bulk",
        "list",
        "junk",
        "vacation",
        "out of office",
        "ooo",
        "autoreply",
        "auto-reply",
    ]
    
    def __init__(self, config: ServiceNowConfig = None):
        """
        Initialize the ServiceNow MCP client.
        
        Args:
            config: ServiceNowConfig instance. If None, loads from env file.
        """
        self.config = config or ServiceNowConfig.from_env_file()
        self._client: Optional[Client] = None
        self._connection_status: Optional[Dict] = None
    
    @property
    def client(self) -> Client:
        """Lazy-load and return pysnow Client."""
        if self._client is None:
            self._client = Client(
                instance=self.config.instance,
                user=self.config.username,
                password=self.config.password
            )
        return self._client
    
    # ───────────────────────────────────────────────
    # 1. HEALTH CHECK
    # ───────────────────────────────────────────────
    
    def health_check(self) -> Dict[str, Any]:
        """
        Verify ServiceNow connection and instance status.
        
        Returns:
            Dict with status, instance info, and any errors.
            
        Raises:
            ConnectionError: If connection fails.
        """
        result = {
            "status": "unknown",
            "instance": self.config.instance,
            "timestamp": datetime.utcnow().isoformat(),
            "connected": False,
            "error": None,
            "details": {}
        }
        
        try:
            # Test connection by querying sys_properties for instance name
            props = self.client.resource(api_path="/table/sys_properties")
            response = props.get(
                query={"name": "instance_name"},
                parameters={"sysparm_limit": 1}
            )
            records = response.all()
            
            if records:
                result["details"]["instance_name"] = records[0].get("value", "unknown")
            
            # Check if instance is active by querying stats.do
            stats = self.client.session.get(
                f"{self.config.base_url}/stats.do",
                timeout=10
            )
            result["details"]["stats_status"] = stats.status_code
            
            result["status"] = "healthy"
            result["connected"] = True
            self._connection_status = result
            
        except pysnow.exceptions.NoResults:
            # Instance exists but no properties found - still connected
            result["status"] = "healthy"
            result["connected"] = True
            self._connection_status = result
            
        except Exception as e:
            result["status"] = "unhealthy"
            result["error"] = str(e)
            self._connection_status = result
            raise ConnectionError(f"ServiceNow connection failed: {e}") from e
        
        return result
    
    def is_healthy(self) -> bool:
        """Quick check if ServiceNow is reachable."""
        try:
            status = self.health_check()
            return status["connected"]
        except ConnectionError:
            return False
    
    # ───────────────────────────────────────────────
    # 2. GET EMAILS FROM sys_email
    # ───────────────────────────────────────────────
    
    def get_emails(
        self,
        limit: int = 10,
        filters: Optional[Dict[str, str]] = None,
        order_by: str = "sys_created_on",
        order_desc: bool = True,
        query_string: Optional[str] = None,
        fields: Optional[List[str]] = None
    ) -> List[Dict[str, Any]]:
        """
        Fetch records from the sys_email table.
        
        Args:
            limit: Maximum number of records to return.
            filters: Dict of field-value pairs to filter by (e.g., {"type": "received"}).
            order_by: Field to sort by.
            order_desc: Sort descending (newest first) if True.
            query_string: Raw encoded query string (overrides filters).
            fields: Specific fields to return (None = all).
            
        Returns:
            List of email record dictionaries.
            
        Raises:
            ConnectionError: If not connected to ServiceNow.
        """
        if not self.is_healthy():
            self.health_check()  # Will raise if truly broken
        
        emails_resource = self.client.resource(api_path="/table/sys_email")
        
        params = {"sysparm_limit": limit}
        if fields:
            params["sysparm_fields"] = ",".join(fields)
        
        # Build query
        if query_string:
            params["sysparm_query"] = query_string
        elif filters:
            query_parts = []
            for field, value in filters.items():
                query_parts.append(f"{field}={value}")
            params["sysparm_query"] = "^".join(query_parts)
        
        # Add ordering
        if order_desc:
            params["sysparm_query"] = params.get("sysparm_query", "") + f"^ORDERBYDESC{order_by}"
        else:
            params["sysparm_query"] = params.get("sysparm_query", "") + f"^ORDERBY{order_by}"
        
        # Clean up query string
        if "sysparm_query" in params:
            params["sysparm_query"] = params["sysparm_query"].strip("^")
        
        try:
            response = emails_resource.get(parameters=params)
            records = response.all()
            
            # Convert to plain dicts
            return [dict(r) for r in records]
            
        except pysnow.exceptions.NoResults:
            return []
        except Exception as e:
            raise ServiceNowMCPError(f"Failed to fetch emails: {e}") from e
    
    def get_email_by_id(self, sys_id: str) -> Optional[Dict[str, Any]]:
        """Fetch a single email record by sys_id."""
        emails = self.get_emails(limit=1, filters={"sys_id": sys_id})
        return emails[0] if emails else None
    
    def get_emails_by_recipient(
        self,
        recipient: str,
        limit: int = 10,
        since: Optional[datetime] = None
    ) -> List[Dict[str, Any]]:
        """
        Get emails sent to a specific recipient.
        
        Args:
            recipient: Email address to search for.
            limit: Max results.
            since: Only return emails after this datetime.
        """
        filters = {"recipient": recipient}
        query_parts = [f"recipient={recipient}"]
        
        if since:
            since_str = since.strftime("%Y-%m-%d %H:%M:%S")
            query_parts.append(f"sys_created_on>={since_str}")
        
        return self.get_emails(
            limit=limit,
            query_string="^".join(query_parts)
        )
    
    # ───────────────────────────────────────────────
    # 3. CREATE RECORDS (Email / Incident)
    # ───────────────────────────────────────────────
    
    def create_record(
        self,
        table: str,
        data: Dict[str, Any],
        dedup_field: Optional[str] = None,
        dedup_value: Optional[str] = None,
        check_watermark: bool = False,
        watermark_data: Optional[Dict[str, str]] = None
    ) -> Dict[str, Any]:
        """
        Create a new record in ServiceNow.
        
        Args:
            table: Table name (e.g., "sys_email", "incident").
            data: Record fields to create.
            dedup_field: Field to check for duplicates (e.g., "subject").
            dedup_value: Value to check for duplicates. If None, uses data[dedup_field].
            check_watermark: If True, check for auto-reply headers before creating.
            watermark_data: Dict of email headers to check for watermarks.
            
        Returns:
            Created record dict with sys_id.
            
        Raises:
            RecordExistsError: If deduplication finds existing record.
            WatermarkDetectedError: If auto-reply detected.
            ServiceNowMCPError: On other failures.
        """
        # 1. Check watermark if email data provided
        if check_watermark and watermark_data:
            if self.detect_watermark(watermark_data):
                raise WatermarkDetectedError(
                    "Auto-reply/watermark detected - refusing to create record to prevent email loop"
                )
        
        # 2. Deduplication check
        if dedup_field:
            check_value = dedup_value or data.get(dedup_field)
            if check_value:
                existing = self.check_duplicate(table, dedup_field, check_value)
                if existing:
                    raise RecordExistsError(
                        f"Record with {dedup_field}='{check_value}' already exists: {existing.get('sys_id')}"
                    )
        
        # 3. Create the record
        try:
            resource = self.client.resource(api_path=f"/table/{table}")
            response = resource.create(payload=data)
            
            # Handle pysnow response properly
            if hasattr(response, 'get'):
                result = response
            elif isinstance(response, dict):
                result = response
            else:
                result = {"result": response, "_created": True}
            
            result["_created"] = True
            return result
            
        except Exception as e:
            raise ServiceNowMCPError(f"Failed to create record in {table}: {e}") from e
    
    def create_email(
        self,
        recipient: str,
        subject: str,
        body: str,
        sender: Optional[str] = None,
        email_type: str = "send-ready",
        check_watermark: bool = True,
        headers: Optional[Dict[str, str]] = None,
        **extra_fields
    ) -> Dict[str, Any]:
        """
        Create an email record in sys_email.
        
        Args:
            recipient: To address.
            subject: Email subject.
            body: Email body content.
            sender: From address (defaults to instance email).
            email_type: Email type ("send-ready", "received", etc.).
            check_watermark: Check for auto-reply headers.
            headers: Email headers dict for watermark detection.
            **extra_fields: Additional sys_email fields.
            
        Returns:
            Created email record.
        """
        data = {
            "type": email_type,
            "recipient": recipient,
            "subject": subject,
            "body": body,
            **extra_fields
        }
        if sender:
            data["sender"] = sender
        
        return self.create_record(
            table="sys_email",
            data=data,
            dedup_field="subject",
            dedup_value=subject,
            check_watermark=check_watermark,
            watermark_data=headers or {}
        )
    
    def create_incident(
        self,
        short_description: str,
        caller: Optional[str] = None,
        category: Optional[str] = None,
        priority: Optional[int] = None,
        description: Optional[str] = None,
        check_duplicate: bool = True,
        **extra_fields
    ) -> Dict[str, Any]:
        """
        Create an incident record.
        
        Args:
            short_description: Brief description (used for dedup if enabled).
            caller: Caller ID or email.
            category: Incident category.
            priority: Priority (1=Critical, 2=High, 3=Moderate, 4=Low).
            description: Detailed description.
            check_duplicate: Check for existing incident with same short_description.
            **extra_fields: Additional incident fields.
            
        Returns:
            Created incident record.
        """
        data = {
            "short_description": short_description,
            **extra_fields
        }
        if caller:
            data["caller_id"] = caller
        if category:
            data["category"] = category
        if priority:
            data["priority"] = priority
        if description:
            data["description"] = description
        
        return self.create_record(
            table="incident",
            data=data,
            dedup_field="short_description" if check_duplicate else None,
            check_watermark=False
        )
    
    # ───────────────────────────────────────────────
    # 4. DEDUPLICATION LOGIC
    # ───────────────────────────────────────────────
    
    def check_duplicate(
        self,
        table: str,
        field: str,
        value: str,
        time_window_hours: Optional[int] = None
    ) -> Optional[Dict[str, Any]]:
        """
        Check if a record with the given field value already exists.
        
        Args:
            table: Table to search.
            field: Field name to match.
            value: Value to search for.
            time_window_hours: Only check records created within this many hours.
            
        Returns:
            Existing record dict if found, None otherwise.
        """
        query_parts = [f"{field}={value}"]
        
        if time_window_hours:
            since = datetime.utcnow() - timedelta(hours=time_window_hours)
            since_str = since.strftime("%Y-%m-%d %H:%M:%S")
            query_parts.append(f"sys_created_on>={since_str}")
        
        query = "^".join(query_parts)
        
        try:
            resource = self.client.resource(api_path=f"/table/{table}")
            response = resource.get(
                parameters={
                    "sysparm_limit": 1,
                    "sysparm_query": query
                }
            )
            records = response.all()
            
            if records:
                return dict(records[0])
            return None
            
        except pysnow.exceptions.NoResults:
            return None
        except Exception as e:
            raise ServiceNowMCPError(f"Deduplication check failed: {e}") from e
    
    def find_duplicates(
        self,
        table: str,
        fields: List[str],
        values: List[str],
        time_window_hours: Optional[int] = None
    ) -> List[Dict[str, Any]]:
        """
        Find records matching multiple field-value pairs.
        
        Args:
            table: Table to search.
            fields: List of field names.
            values: List of values (must match fields length).
            time_window_hours: Time window for created records.
            
        Returns:
            List of matching records.
        """
        if len(fields) != len(values):
            raise ValueError("fields and values must have same length")
        
        query_parts = [f"{f}={v}" for f, v in zip(fields, values)]
        
        if time_window_hours:
            since = datetime.utcnow() - timedelta(hours=time_window_hours)
            since_str = since.strftime("%Y-%m-%d %H:%M:%S")
            query_parts.append(f"sys_created_on>={since_str}")
        
        query = "^".join(query_parts)
        
        try:
            resource = self.client.resource(api_path=f"/table/{table}")
            response = resource.get(
                parameters={
                    "sysparm_limit": 100,
                    "sysparm_query": query
                }
            )
            records = response.all()
            return [dict(r) for r in records]
            
        except pysnow.exceptions.NoResults:
            return []
        except Exception as e:
            raise ServiceNowMCPError(f"Duplicate search failed: {e}") from e
    
    # ───────────────────────────────────────────────
    # 5. WATERMARK DETECTION (Email Loop Prevention)
    # ───────────────────────────────────────────────
    
    def detect_watermark(self, headers: Dict[str, str]) -> bool:
        """
        Detect auto-reply/watermark headers to prevent email loops.
        
        Checks for common auto-reply header names and values that indicate
        automated responses (out-of-office, bouncebacks, mailing lists, etc.).
        
        Args:
            headers: Dict of email headers (case-insensitive keys).
            
        Returns:
            True if watermark/auto-reply detected.
        """
        if not headers:
            return False
        
        # Normalize headers to lowercase
        normalized = {k.lower().strip(): str(v).lower().strip() for k, v in headers.items()}
        
        # Check 1: Known auto-reply header names
        for header_name in self.WATERMARK_HEADERS:
            if header_name in normalized:
                return True
        
        # Check 2: Header values indicating auto-reply
        for header_name, header_value in normalized.items():
            for watermark_val in self.WATERMARK_VALUES:
                if watermark_val in header_value:
                    return True
        
        # Check 3: Subject line patterns (common auto-reply subjects)
        subject = normalized.get("subject", "")
        auto_reply_patterns = [
            r"^out of( the)? office",
            r"^auto.?(reply|response)",
            r"^vacation",
            r"^away from office",
            r"^undeliverable",
            r"^delivery status notification",
            r"^mail delivery failed",
            r"^bounce",
            r"^\[auto",
        ]
        for pattern in auto_reply_patterns:
            if re.search(pattern, subject, re.IGNORECASE):
                return True
        
        # Check 4: From address patterns (noreply, mailer-daemon, etc.)
        from_addr = normalized.get("from", "")
        noreply_patterns = [
            r"noreply@",
            r"no-reply@",
            r"mailer-daemon@",
            r"postmaster@",
            r"bounce@",
            r"autoreply@",
            r"auto-reply@",
            r"outofoffice@",
            r"vacation@",
        ]
        for pattern in noreply_patterns:
            if re.search(pattern, from_addr, re.IGNORECASE):
                return True
        
        return False
    
    def get_watermark_reason(self, headers: Dict[str, str]) -> Optional[str]:
        """
        Get human-readable reason for watermark detection.
        
        Returns:
            String explaining why it was flagged, or None if not detected.
        """
        if not headers:
            return None
        
        normalized = {k.lower().strip(): str(v).lower().strip() for k, v in headers.items()}
        
        # Check header names
        for header_name in self.WATERMARK_HEADERS:
            if header_name in normalized:
                return f"Auto-reply header detected: {header_name}={normalized[header_name]}"
        
        # Check values
        for header_name, header_value in normalized.items():
            for watermark_val in self.WATERMARK_VALUES:
                if watermark_val in header_value:
                    return f"Auto-reply value detected in {header_name}: {header_value}"
        
        # Check subject
        subject = normalized.get("subject", "")
        if re.search(r"^out of( the)? office", subject, re.IGNORECASE):
            return "Out-of-office auto-reply detected in subject"
        if re.search(r"^auto.?(reply|response)", subject, re.IGNORECASE):
            return "Auto-reply detected in subject"
        if re.search(r"^undeliverable", subject, re.IGNORECASE):
            return "Bounce/undeliverable message detected"
        
        # Check from address
        from_addr = normalized.get("from", "")
        if re.search(r"(noreply|no-reply|mailer-daemon|postmaster|bounce)@", from_addr, re.IGNORECASE):
            return f"No-reply/bounce address detected: {from_addr}"
        
        return None
    
    # ───────────────────────────────────────────────
    # UTILITY METHODS
    # ───────────────────────────────────────────────
    
    def generate_fingerprint(self, data: Dict[str, Any], fields: List[str]) -> str:
        """
        Generate a hash fingerprint for deduplication across multiple fields.
        
        Args:
            data: Record data.
            fields: Fields to include in fingerprint.
            
        Returns:
            MD5 hash string for comparison.
        """
        values = []
        for field in fields:
            val = data.get(field, "")
            values.append(str(val).strip().lower())
        
        fingerprint = "|".join(values)
        return hashlib.md5(fingerprint.encode()).hexdigest()
    
    def get_connection_status(self) -> Optional[Dict[str, Any]]:
        """Return cached connection status from last health check."""
        return self._connection_status


# ───────────────────────────────────────────────────
# CLI / Direct Execution
# ───────────────────────────────────────────────────

def main():
    """CLI entry point for quick tests."""
    import argparse
    
    parser = argparse.ArgumentParser(description="ServiceNow MCP Integration")
    parser.add_argument("action", choices=["health", "emails", "create-email", "create-incident"])
    parser.add_argument("--limit", type=int, default=5)
    parser.add_argument("--recipient", default="test@example.com")
    parser.add_argument("--subject", default="Test Subject")
    parser.add_argument("--body", default="Test body content")
    parser.add_argument("--description", default="Test incident")
    
    args = parser.parse_args()
    
    mcp = ServiceNowMCP()
    
    if args.action == "health":
        result = mcp.health_check()
        print(json.dumps(result, indent=2))
        
    elif args.action == "emails":
        emails = mcp.get_emails(limit=args.limit)
        print(f"Found {len(emails)} emails:")
        for e in emails:
            print(f"  - {e.get('sys_id')}: {e.get('subject', 'N/A')} -> {e.get('recipient', 'N/A')}")
            
    elif args.action == "create-email":
        try:
            result = mcp.create_email(
                recipient=args.recipient,
                subject=args.subject,
                body=args.body
            )
            print(f"Created email: {result.get('sys_id')}")
        except RecordExistsError as e:
            print(f"Duplicate detected: {e}")
        except WatermarkDetectedError as e:
            print(f"Watermark detected: {e}")
            
    elif args.action == "create-incident":
        try:
            result = mcp.create_incident(
                short_description=args.description,
                caller="admin"
            )
            print(f"Created incident: {result.get('number')} ({result.get('sys_id')})")
        except RecordExistsError as e:
            print(f"Duplicate detected: {e}")


if __name__ == "__main__":
    main()
